name: Bug Report
description: Report a bug with the StrawberrySMP
labels: ["Bug: Unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making a report! Please make sure to provide the following
        1. Screenshots in available
        2. Make sure the issue hasnt been reported yet.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Describe the bug in as best as you can.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Please leave a instructions to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: Screenshots and/or videos of the bug in action.
      placeholder: |-
        link to images etc, 
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What minecraft version where you using?
      options:
        - 1.20
        - 1.20.1
        - 1.20.2
        - 1.20.3
        - 1.20.4
        - 1.20.5
      default: 1
    validations:
      required: true
